### PR TITLE
Added terraform 0.7.4 package

### PR DESCRIPTION
**Pull request by toplac**
Adds package for the provisioning tool terraform version 0.7.4

### CODE REVIEW

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:
- Pull request description cannot be empty [(?)](https://gitmagic.io/rules/#/pull-request/body-cannot-be-empty)
- Pull request title must be in past tense (e.g. "added", "fixed", "changed") [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/34/559eb7c1-a8a9-4704-8942-7ea27cce007d/fee69988-9198-4f63-b13f-4fc19bd14997) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This pull request still violates some of our guidelines:
- Pull request title must be in past tense (e.g. "added", "fixed", "changed") [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/34/559eb7c1-a8a9-4704-8942-7ea27cce007d/fee69988-9198-4f63-b13f-4fc19bd14997) for details.

**Comment by ghost** [comment]
Thank you, the title and description now looks good! :bowtie:

**Comment by toplac** [comment]
Aborted du to gitmagic violations. 
Will fix the violations and open a new PR

**Pull request closed without merging**
