### PR TITLE
Added new package for OpenJDK8 under windows

### PR DESCRIPTION
**Pull request by chr-fritz**
Uses the community built package from: https://github.com/ojdkbuild/ojdkbuild
Prebuilt packages for macOS don't exits.

### CODE REVIEW

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:

* Pull request title must not end with a dot [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-not-end-with-dot)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/64/559eb7c1-a8a9-4704-8942-7ea27cce007d/3ca342c9-e02d-48c3-b365-f7763f5978e4) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, the title and description now looks good! :bowtie:

**Comment by lreimer** [comment]
Ach du grüne Neune. Ist die Quelle vertrauenswürdig??
Hast du schon mal das hier versucht: https://adoptopenjdk.net
Haben leider kein 8u161 hier.

**Comment by chr-fritz** [comment]
Changed to adoptopenjdk and added variants for macOS and linux.

**Comment by lreimer** [comment]
Changed software dependency coordinate to `net.adoptopenjdk:openjdk8:8u141-b01`

**Pull request merged**
